args_path: null
centroid_weight: 0.2
checkpoint_path: null
device: cuda:0
disable_randperm: true
dist_url: env://
do_add_noise_to_real_data: false
do_benchmark: false
do_calc_dist_metrics: true
do_noisify: true
do_not_calc_dist_metrics: false
do_optimize: false
do_overfit: false
do_rescale_lr: false
do_save_model: false
do_vis_entire_batch: false
dropout_rate: 0.4
early_stop_delta: 0.002
early_stop_n_epochs: 60
exp_disabled: false
exp_tags:
- exp_minkowski
flat_region_z_lower_limit: -0.5
flat_region_z_upper_limit: 0.5
gt_pts_scaler: 1
hidden_dims_scaler: 2.0
hp_group_ignored: []
hp_group_num: null
ignored_file_args: []
log_every_n_epochs: 10
log_subdir: terrain_ds_v13
lr: 0.0005
lr_decay: 0.995
map_dimension: 64
map_resolution_xy: 0.3125
map_resolution_z: 0.3125
mesh_cell_resolution: 0.1
mini_batch_size: 16
model_name: unet
noise_add_blobs_prob: 0.7
noise_add_boxes_prob: 0.7
noise_apply_mask_prob: 0.0
noise_apply_rotation_prob: 0.7
noise_apply_shift_prob: 1.0
noise_blob_extent: 0.3
noise_noise_scale: 0.01
noise_num_blob_points: 30
noise_num_blobs: 5
noise_prob: 1.0
noise_subsampling_ratio_max: 0.9
noise_subsampling_ratio_min: 0.2
norm_layer_name: layer_norm
num_epochs: 500
num_pts: null
num_workers: 0
occupancy_threshold: 0.5
opt_n_epochs: 10
opt_n_jobs: 2
opt_n_trials: 7
opt_params_to_tune: []
opt_storage: postgresql://optuna:optuna@localhost:5432/optuna_studies
opt_study_prefix: opt
opt_target_metrics: f1
overfit_num_scans_in_traj: 1
overfit_num_terrains: 1
overfit_num_traj_per_terrain: 1
overfit_scan_idxs: null
overfit_traj_idxs: null
pflow_use_gen: false
plots_disabled: true
plots_interactive: false
plots_zoom: 0.5
pos_weight: 5.0
real_ds_bremgarten_folder: /abs/path/to/data/real/armano_bremgarten/parsed/sunavigation
real_ds_hong2_folder: /abs/path/to/data/real/hong_30_07_24/parsed/subset
real_ds_hong_folder: /abs/path/to/data/real
run_name: medical_cattle_6018
save_every_n_epochs: 10
seed: 500
seed_loss_coef: 0.1
sequence_length: 1
similar_dist_thresh: 0.02
sl_do_flatten_batch_dim: false
sl_use_full_triplet_loss: false
start_dist_metrics_from_n_epoch: 0
start_mae_from_n_epoch: 0
stdout_log_file: terrain_ds_v13_sparse_unet_minkowski_64_2024_09_06_11_00_22.log
step_skip: 1
test_freq_epoch: 20
traj_folder: /abs/path/to/data/terrain_ds_v13/collected_data_tilted/OS0_128ch10hz512res_processed_no_mask
triplet_loss_margin: 4.0
unsup_seed_subsample_ratio: 0.25
use_async_vis: false
use_centroids_for_dist_loss: false
use_chamfer_loss: true
use_cylindrical_coords: false
use_dataloader: true
use_ddp: false
use_dropout: true
use_early_stopping: true
use_extended_input: false
use_large_model: false
use_mae_loss: false
use_occupancy_loss_with_input: false
use_pc_norm: false
use_prev_pred_as_input: false
use_randperm: false
use_real_ds_in_train: false
use_seed_loss: false
use_seed_loss_unsup: false
use_skip_conn: false
use_sparse: true
use_val_ds: true
vis_disabled: false
vis_enabled: true
vis_freq_batch_per_epoch: 2
vis_freq_epoch: 5
